// <auto-generated />
namespace Forge.Museum.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedImageFileTypePropToArtefact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedImageFileTypePropToArtefact));
        
        string IMigrationMetadata.Id
        {
            get { return "201808130106229_AddedImageFileTypePropToArtefact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
